# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('gameStatus', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gamedata',
            unique_together=set([('gameID', 'username')]),
        ),
    ]
