# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20160208_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
