# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20160209_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='highScore',
            field=models.IntegerField(default=0),
        ),
    ]
