# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0014_auto_20160205_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 2, 8)),
        ),
    ]
