# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0015_auto_20160208_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 8, 8, 30, 5, 167579, tzinfo=utc)),
        ),
    ]
